adjusted share-detail into share shell with comment component
KanoComputing/world pull request #29
Opened 2016-11-29 12:35 UTC by etamity

2016-12-03 14:27 UTC, vikdoro commented on src/elements/kw-share-detail/kw-share-detail.html
> +					<kw-social-comment share=[[share]]></kw-social-comment>
speech marks missing from around the share attribute value

2016-12-03 14:27 UTC, vikdoro commented on src/elements/kw-share-detail/kw-share-detail.html
> +				display: block;
my css remarks in the previous reviews would apply here as well :)

2016-12-05 11:57 UTC, etamity commented
@vikdoro updated from code reviews

2016-12-14 16:33 UTC, arifshanji requested changes

2016-12-14 16:33 UTC, arifshanji commented on src/elements/kw-share-detail/kw-share-detail.html
> +				@apply --layout-vertical;
4 spaces please

2016-12-20 17:59 UTC, etamity commented
@arifshanji @pazdera the style has been updated

2016-12-21 17:49 UTC, arifshanji approved these changes

2016-12-21 17:51 UTC, paulvarache reviewed
Still issues with indentation.
The remix action is not implemented

2016-12-21 21:00 UTC, etamity commented
@paulvarache Thanks for the review 🥇 :)

2016-12-23 11:34 UTC, paulvarache commented on src/elements/kw-share-detail/kw-share-detail.html
> +                var pathname = window.location.pathname.replace('/shares/','/remix/');
Not every share is a Kano Code share

2016-12-28 10:32 UTC, merged